# Generated by Django 5.0.6 on 2024-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_participant_meet_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='date',
            field=models.DateField(default='2024-04-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='organizer_email',
            field=models.EmailField(default='2021-04-12', max_length=254),
            preserve_default=False,
        ),
    ]
