# Generated by Django 5.0.6 on 2024-06-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meet_date_meet_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='date',
        ),
    ]
