# Generated by Django 5.0.6 on 2024-06-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_remove_meet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='organizer_email',
        ),
    ]
