# Generated by Django 5.0.6 on 2024-06-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_remove_meet_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='date',
            field=models.DateField(default='2022-07-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='organizer_email',
            field=models.EmailField(default='yonasamsalu75@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
